### ISSUE TITLE
Test events

### ISSUE THREAD

**Issue by suzuki-shunsuke** [gha-trigger/gha-trigger#50]
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows

- [ ] branch_protection_rule
- [ ] check_run
- [ ] check_suite
- [ ] create
- [ ] delete
- [ ] deployment
- [ ] deployment_status
- [ ] discussion
  - [x] created
  - [ ] edited
  - [ ] deleted
  - [ ] transferred
  - [ ] pinned
  - [ ] unpinned
  - [ ] labeled
  - [ ] unlabeled
  - [ ] locked
  - [ ] unlocked
  - [ ] category_changed
  - [ ] answered
  - [ ] unanswered
- [ ] discussion_comment https://pkg.go.dev/github.com/google/go-github/v47/github#ParseWebHook doesn't support discussion_comment
  - [ ] created https://github.com/gha-trigger/gha-trigger/issues/106
  - [ ] edited
  - [ ] deleted
- [x] fork
- [ ] gollum
- [x] ⭐ issue_comment
  - [x] ⭐ slash command
  - [ ] ⭐ workflow
    - [ ] pr
    - [ ] issue
- [ ] issues
  - [x] opened
  - [ ] edited
  - [ ] deleted
  - [ ] transferred
  - [ ] pinned
  - [ ] unpinned
  - [ ] closed
  - [ ] reopened
  - [ ] assigned
  - [ ] unassigned
  - [ ] labeled
  - [ ] unlabeled
  - [ ] locked
  - [ ] unlocked
  - [ ] milestoned
  - [ ] demilestoned
- [ ] label
  - [x] created
  - [ ] edited
  - [ ] deleted
- [ ] merge_group
- [ ] milestone
  - [x] created
  - [ ] closed
  - [ ] opened
  - [ ] edited
  - [ ] deleted
- [ ] page_build
- [ ] project
  - [ ] created
  - [ ] closed
  - [ ] reopened
  - [ ] edited
  - [ ] deleted
- [ ] project_card
- [ ] project_column
- [ ] public
- [ ] ⭐ pull_request
  - [x] assigned
  - [x] unassigned
  - [x] labeled
  - [x] unlabeled
  - [x] opened
  - [x] edited
  - [ ] closed
  - [x] reopened
  - [x] synchronize
  - [ ] converted_to_draft
  - [ ] ready_for_review
  - [x] locked
  - [x] unlocked
  - [ ] review_requested
  - [ ] review_request_removed
  - [ ] auto_merge_enabled
  - [ ] auto_merge_disabled
- [x] ⭐ pull_request_comment (use issue_comment)
- [ ] pull_request_review
- [ ] pull_request_review_comment
- [x] ⭐ pull_request_target
  - [ ] assigned
  - [ ] unassigned
  - [ ] labeled
  - [ ] unlabeled
  - [ ] opened
  - [ ] edited
  - [ ] closed
  - [ ] reopened
  - [ ] synchronize
  - [ ] converted_to_draft
  - [ ] ready_for_review
  - [ ] locked
  - [ ] unlocked
  - [ ] review_requested
  - [ ] review_request_removed
  - [ ] auto_merge_enabled
  - [ ] auto_merge_disabled
- [ ] push
  - [x] ⭐ branch
  - [x] ⭐ tag
  - [ ] ⭐ delete branch 
- [ ] registry_package
- [ ] ⭐ release
  - [ ] published
  - [ ] unpublished
  - [x] created
  - [ ] edited
  - [ ] deleted
  - [x] prereleased
  - [ ] released
- [ ] repository_dispatch
- [ ] schedule
- [ ] status
- [ ] watch
- [ ] workflow_call
- [ ] workflow_dispatch
- [ ] workflow_run

**Comment by suzuki-shunsuke** [comment]
# Problems

- delete branch and tag: Webhook's `push` event includes `create` and `delete` event
- discussion_comment: [go-github/v47#ParseWebHook](https://pkg.go.dev/github.com/google/go-github/v47/github#ParseWebHook) doesn't support discussion_comment

## TODO

- pull_request closed
- pull_request_target

**Comment by suzuki-shunsuke** [comment]
> discussion_comment: [go-github/v47#ParseWebHook](https://pkg.go.dev/github.com/google/go-github/v47/github#ParseWebHook) doesn't support discussion_comment

We stop using `ParseWebHook`, so this problem has been solved.

**Comment by suzuki-shunsuke** [comment]
Done.
